### ISSUE TITLE
_tkinter.TclError: character U+1f6a9 is above the range (U+0000-U+FFFF) allowed by Tcl

### ISSUE THREAD

**Issue by Samonac** [haveaLukeatthis/SelfSolvingMinesweeper#3]
```
C:\Users\samon\PycharmProjects\277777788888899_project\venv\Scripts\python.exe C:/Users/samon/Desktop/HALAT-MineAndSolve.py
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\samon\AppData\Local\Programs\Python\Python37\Lib\tkinter\__init__.py", line 1702, in __call__
    return self.func(*args)
  File "C:\Users\samon\AppData\Local\Programs\Python\Python37\Lib\tkinter\__init__.py", line 746, in callit
    func(*args)
  File "C:/Users/samon/Desktop/HALAT-MineAndSolve.py", line 135, in spiral
    FlagClick(xtemp+1,ytemp-1,indextemp+1-numOfCols)
  File "C:/Users/samon/Desktop/HALAT-MineAndSolve.py", line 37, in FlagClick
    btnBox.config(text="🚩")
  File "C:\Users\samon\AppData\Local\Programs\Python\Python37\Lib\tkinter\__init__.py", line 1482, in configure
    return self._configure('configure', cnf, kw)
  File "C:\Users\samon\AppData\Local\Programs\Python\Python37\Lib\tkinter\__init__.py", line 1473, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: character U+1f6a9 is above the range (U+0000-U+FFFF) allowed by Tcl

```

Windows 10 & Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51)

**Comment by quasar098** [comment]
A fix is at fork https://github.com/shah253kt/SelfSolvingMinesweeper

**Comment by AverageComet250** [comment]
Can you submit a pr for the fix. Hopefully it'll be merged

**Comment by kenan238** [comment]
> A fix is at fork https://github.com/shah253kt/SelfSolvingMinesweeper

Would be great if you turned it into a PR.

**Comment by quasar098** [comment]
i can't it doesn't let me i dont know why
![image](https://user-images.githubusercontent.com/70716985/221326874-2fdbaef1-42d7-4195-85b1-da55e03d8057.png)

**Comment by Samonac** [comment]
> A fix is at fork https://github.com/shah253kt/SelfSolvingMinesweeper

I tried cloning your fork, but same issue still : 

`Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\samon\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 1702, in __call__
    return self.func(*args)
  File "C:\Users\samon\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 746, in callit
    func(*args)
  File "C:/Users/samon/OneDrive/Documents/git/github/SelfSolvingMinesweeper/HALAT-MineAndSolve.py", line 134, in spiral
    FlagClick(xtemp-1,ytemp-1,indextemp-1-numOfCols)
  File "C:/Users/samon/OneDrive/Documents/git/github/SelfSolvingMinesweeper/HALAT-MineAndSolve.py", line 39, in FlagClick
    btnBox.config(text="🚩")
  File "C:\Users\samon\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 1482, in configure
    return self._configure('configure', cnf, kw)
  File "C:\Users\samon\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 1473, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: character U+1f6a9 is above the range (U+0000-U+FFFF) allowed by Tcl
`
